print("英雄联盟")
character = input("请输入人物角色：")
initial_equipment = input("请输入角色的初始装备：")
equipment1 = input("请输入购买第二件装备的名称:")
price1 = float(input("请输入第一件装备的价钱："))
equipment2 = input("请输入购买第三件装备的名称:")
price2 = float(input("请输入第二件装备的价钱："))
equipment3 = input("请输入购买第四件装备的名称:")
price3 = float(input("请输入第三件装备的价钱："))
print("%s购买装备有%s,%s,%s,总花费的价钱是%f"%(character,equipment1,equipment2,equipment3,price1+price2+price3))